# Generated by Django 4.2.3 on 2023-07-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_profile_pic_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('T-shirts', 'T-shirts'), ('Jeans', 'Jeans')], max_length=100)),
                ('product_brand', models.CharField(choices=[('Adidas', 'Adidas'), ('Allen Solly', 'Allen Solly'), ('Netplay', 'Netplay'), ('Performax', 'Performax'), ('Lee Cooper', 'Lee Copper'), ('Wrangler', 'Wrangler'), ('Spykar', 'Spykar'), ('Levis', 'Levis')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=100)),
                ('product_pic', models.ImageField(upload_to='profile_pic/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
