# Generated by Django 4.2.3 on 2023-07-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(choices=[('Superdry', 'Superdry'), ('Allen Solly', 'Allen Solly'), ('Netplay', 'Netplay'), ('Performax', 'Performax'), ('Levis', 'Levis')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Round', 'Round'), ('Polo', 'Polo'), ('V-Neck', 'V-Neck'), ('Sports', 'Sports')], max_length=100),
        ),
    ]
