# Generated by Django 4.2.3 on 2023-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Round', 'Round'), ('Polo', 'Polo'), ('Full Sleeve', 'Full Sleeve'), ('Sports', 'Sports')], max_length=100),
        ),
    ]
